// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Appbar: typeof import('./src/components/layout/appbar.vue')['default']
    Footer: typeof import('./src/components/layout/footer.vue')['default']
    Sidebar: typeof import('./src/components/details/sidebar.vue')['default']
    VApp: typeof import('vuetify/lib')['VApp']
    VAppBar: typeof import('vuetify/lib')['VAppBar']
    VAppBarNavIcon: typeof import('vuetify/lib')['VAppBarNavIcon']
    VAvatar: typeof import('vuetify/lib')['VAvatar']
    VBtn: typeof import('vuetify/lib')['VBtn']
    VCard: typeof import('vuetify/lib')['VCard']
    VCardText: typeof import('vuetify/lib')['VCardText']
    VChip: typeof import('vuetify/lib')['VChip']
    VCol: typeof import('vuetify/lib')['VCol']
    VContainer: typeof import('vuetify/lib')['VContainer']
    VDivider: typeof import('vuetify/lib')['VDivider']
    VFooter: typeof import('vuetify/lib')['VFooter']
    VHover: typeof import('vuetify/lib')['VHover']
    VIcon: typeof import('vuetify/lib')['VIcon']
    VImg: typeof import('vuetify/lib')['VImg']
    VList: typeof import('vuetify/lib')['VList']
    VListItem: typeof import('vuetify/lib')['VListItem']
    VListItemContent: typeof import('vuetify/lib')['VListItemContent']
    VListItemGroup: typeof import('vuetify/lib')['VListItemGroup']
    VListItemTitle: typeof import('vuetify/lib')['VListItemTitle']
    VMain: typeof import('vuetify/lib')['VMain']
    VNavigationDrawer: typeof import('vuetify/lib')['VNavigationDrawer']
    VRow: typeof import('vuetify/lib')['VRow']
    VSubheader: typeof import('vuetify/lib')['VSubheader']
    VTextField: typeof import('vuetify/lib')['VTextField']
    VToolbarTitle: typeof import('vuetify/lib')['VToolbarTitle']
  }
}

export { }
